baseURL = "zainiya.github.io/"
languageCode = "en-us"
title = "Zainiya Manjiyani Portfolio"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Zainiya Manjiyani, Software Developer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "zaineyamanjiyani@gmail.com"
    facebook = "zaineya.manjiyani"
    twitter = "ZainiyaManjiyan"
    dribbble = "zainiyamanjiyani"
    linkedin = "https://www.linkedin.com/in/zainiyamanjiyani/"
    github = "zainiya"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "zainiya-manjiyani.jpg"
    subtitle = "Hi! I'm Zainiya, a Software Developer from Sacramento."
    hero_right = ["**Currently graduate student at California State University - Sacramento. I am doing my Master of Science in Computer Science with specialization in Software Engineering. Completed multiple challenging class projects which gave in depth precpective for my course studies. Along with my studies I am also working as a software developer at Office of Water Programs.**", 

    "Actively working on developing new website of Office of Water Programs both frontend as well as backend. Along with website developemt, I have build some internal applications also.",

    "Before coming to United States of America I have worked at TATA Consultancy services in Pune, India. Got selected in innovation team member, where active participation of brainstorming new ideas is crucial.",

    "I belong to 2011 batch of Bachelors of Engineering in Computer Science and Engineering from Faculty of Engineering Technology and Research (FETR). FETR is affilated with Gujarat Technological University. My undergrad studies was focused on learning basics which built strong foundation of Computer Science, Data Structure and Algorithms."]
    resume = "ResumeManjiyani.pdf"

[params.process]
    enable = false
    title = "My Process"
    subtitle = "Full UI/UX Design Process"

[params.projects]
    enable = false
    title = "Project Work"
    subtitle = "Selected Works"

[params.achievement]
    enable = true
    title = "Achievements"
    academic = [
    "**Excellence Award** from Educational Committee <span class='badge'>2017" , 
    "Final Year Project have been shortlisted among top 10 innovative projects for **''Dewang Mehta IT Award 2015''** <span class='badge'>2015</span>" , 
    "3<sup>rd</sup> position in 8<sup>th</sup> semester of Bachelor's Degree<span class='badge'>2015</span>" , 
    "Successfully developed **''C-Quest'' software** for VisveSmruti 2K14 (Techfest of FETR, Bardoli) <span class='badge'>2014</span>" , 
    "Given seminar on **''Real Time Tracking of Multiple Fingertips and Gesture Recognition for Augmented Desk Interface System''** <span class='badge'>2014</span>" , 
    "Participated in **''Robo Race''** held at Ayam <span class='badge'>2013</span>" , 
    "Completed **Wireless Sensor Network** workshop <span class='badge'>2014 </span>" , 
    "Completed **Cloud Computing** workshop <span class='badge'>2014</span>" , 
    "3<sup>rd</sup> position in 3<sup>rd</sup> semester of Bachelor's degree <span class='badge'>2013</span>" , 
    "3<sup>rd</sup> position in **Code Spring** held at Ayam <span class='badge'>2013</span>" , 
    "Certified **Ethical Hacking Expert(Level 1)** <span class='badge'>2011</span>" , 
    "1<sup>st</sup> position in class and 8<sup>th</sup> State Rank in **''International Olympiad of Mathematics''** <span class='badge'>2009</span>"
    ]
    extra = [
    "Winner of **Table Tennis Tournament** <span class='badge'>2015</span>" , 
    "Created video for VisveSmruti 2k14 <span class='badge'>2014</span>",
    "Completed **Master Ismaili Scouter Guider Training** Course <span class='badge'>2013</span>" , 
    "Winner of **Table Tennis Tournament** <span class='badge'>2013</span>" , 
    "Winner of **Tug of War** <span class='badge'>2012</span>" , 
    "Runners up in **CHESS tournament**<span class='badge'>2012</span>" , 
    "2<sup>nd</sup> position in **Folk Dance of GTU ''XITIJ-2011''** <span class='badge'>2011</span>" , 
    "Participated in Poster presentation <span class='badge'>2011</span>" , 
    "2<sup>nd</sup> position in **''Math Quiz''** competition <span class='badge'>2010</span>" , 
    "Participated in **''Sudoku inter school''** competition <span class='badge'>2010</span>" , 
    "Winner of **Three Legged Race**<span class='badge'> 2009 </span>" , 
    "Cleared  **National Cadet Corps** certificate ‘A’ Examination with CDT Rank with B grade <span class='badge'> 2008</span>" , 
    "3<sup>rd</sup> position in **Badminton Tournament** <span class='badge'>2007</span>" , 
    "1<sup>st</sup> position in **Drawing Competition** <span class='badge'> 2007 </span>"
    ]

[params.footer]
    enable = true
