baseURL = "zainiya.github.io"
languageCode = "en-us"
title = "Zainiya Manjiyani Portfolio"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Alexis Collado, UX Designer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "zaineyamanjiyani@gmail.com"
    facebook = "zaineya.manjiyani"
    twitter = "ZainiyaManjiyan"
    dribbble = "zainiyamanjiyani"
    linkedin = "https://www.linkedin.com/in/zainiyamanjiyani/"
    github = "zainiya"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "zainiya-manjiyani.jpg"
    subtitle = "Hi! I'm Zainiya, a Software Developer from Sacramento."
    hero_right = ["**Currently student at California State University - Sacramento. Along with my studies I am also working as a software developer at Office of Water Programs. Previously worked as Assistant System Engineer at TATA Consultancy Services in Pune, India.**", "I founded [User Experience Society](https://www.facebook.com/UXSoc/), the first student UX organization in the Philippines. For two years, we've had 20+ events with 30+ speakers for over 300 members and 500+ attendees. We've expanded to [California](https://www.facebook.com/profile.php?id=245708449193012) this year.", "I do a bit of writing as well. [Here's an article with a total of 21,000+ views to InVision & Medium](http://blog.invisionapp.com/ux-internship-wisdom/) talking about 50 things I learned spending 3 years as a UX intern.", "I help cultivate the design community in Manila too. I'm the youngest core member of [UX Philippines](https://www.facebook.com/groups/uxphilippines/) and I moderated a panel with some cool people for the [UXPH 2017 Conference](https://www.uxphilippines.com).", "I'm finishing my Bachelor's degree in Management Information Systems at the Ateneo de Manila University, expecting to graduate in 2018."]
    resume = "ResumeManjiyani.pdf"

[params.process]
    enable = true
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
