baseURL = "zainiya.github.io/"
languageCode = "en-us"
title = "Zainiya Manjiyani Portfolio"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Zainiya Manjiyani, Software Developer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "zaineyamanjiyani@gmail.com"
    facebook = "zaineya.manjiyani"
    twitter = "ZainiyaManjiyan"
    dribbble = "zainiyamanjiyani"
    linkedin = "https://www.linkedin.com/in/zainiyamanjiyani/"
    github = "zainiya"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "zainiya-manjiyani.jpg"
    subtitle = "Hi! I'm Zainiya, a Software Developer from Sacramento."
    hero_right = ["**Currently graduate student at California State University - Sacramento. I am doing my Master of Science in Computer Science with specialization in Software Engineering. Completed multiple challenging class projects which gave in depth precpective for my course studies. Along with my studies I am also working as a software developer at Office of Water Programs.**", 

    "Actively working on developing new website of Office of Water Programs both frontend as well as backend. Along with website developemt, I have build some internal applications also.",

    "Before coming to United States of America I have worked at TATA Consultancy services in Pune, India. Got selected in innovation team member, where active participation of brainstorming new ideas is crucial.",

    "I belong to 2011 batch of Bachelors of Engineering in Computer Science and Engineering from Faculty of Engineering Technology and Research (FETR). FETR is affilated with Gujarat Technological University. My undergrad studies was focused on learning basics which built strong foundation of Computer Science, Data Structure and Algorithms."]
    resume = "ResumeManjiyani.pdf"

[params.process]
    enable = false
    title = "My Process"
    subtitle = "Full UI/UX Design Process"

[params.projects]
    enable = false
    title = "Project Work"
    subtitle = "Selected Works"

[params.achievement]
    enable = true
    title = "Achievements"
    

[params.footer]
    enable = true
